### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by dentx22** [Tang1705/Reconstruction#1]
Interface menu compiled perfectly
but it crashes as soon as it starts
it needs other directories
tnks

**Comment by Tang1705** [comment]
I don't know if you have seen the GUI
I think the project also need some party,i.e. opencv,pcl,vtk and so on
you also need to do some configuration in the project and environment in the computer
what's more, it relys on the camera and projector
Of course, I complete its main function recently  so maybe there are some bugs I didn't find

**Comment by dentx22** [comment]
GUI I see
then after it crashes i don't understand configured with vcpkg

**Comment by Tang1705** [comment]
Sorry I don't meet and understand this problem
And I update a exe file and a doc(write in Chinese) to guide users 
Maybe you can try to click and run it in windows operate system 
Sorry again , I can't offer more help at present
